easy_admin:
    site_name: '<img src="/build/images/logos/logo_black_min.png" width="60" height="64"/>'
    design:
        brand_color: '#1ABC9C'
    entities:
        # List the entity class name you want to manage
        Ad:
            class:  App\Entity\ItemAd
        Item:
            class: App\Entity\Item
        Category:
            class : App\Entity\Category
        User:
            class: App\Entity\User
